name: ur_store
description: "ur store"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  connectivity_plus: ^6.0.2
  cupertino_icons: ^1.0.6
  get_it: ^7.7.0
  injectable: ^2.4.1
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  json_serializable: ^6.7.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  envied: ^0.5.3
  package_info_plus: ^5.0.1
  auto_route: ^8.1.3
  google_fonts: ^6.2.1
  sqflite: ^2.4.1
  path: ^1.8.0
  uuid: ^4.5.1
  intl: ^0.19.0
  shimmer: ^3.0.0
dev_dependencies:
  build_runner: ^2.4.8
  injectable_generator: ^2.3.0
  flutter_gen_runner: ^5.3.2
  mockito: ^5.4.4
  bloc_test: ^9.1.6
  hive_generator: ^2.0.0
  envied_generator: ^0.5.3
  auto_route_generator: ^8.0.0

  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/app/


